export const professions = [
  { value: 'nails', label: 'Körmös' },
  { value: 'lashes', label: 'Műszempillás' },
  { value: 'hair', label: 'Fodrász' },
  { value: 'cosmetics', label: 'Kozmetikus' },
  { value: 'makeup', label: 'Sminkes' },
  { value: 'barber', label: 'Borbély' },
];

export const budapestDistricts = [
  'I. kerület',
  'II. kerület',
  'III. kerület',
  'IV. kerület',
  'V. kerület',
  'VI. kerület',
  'VII. kerület',
  'VIII. kerület',
  'IX. kerület',
  'X. kerület',
  'XI. kerület',
  'XII. kerület',
  'XIII. kerület',
  'XIV. kerület',
  'XV. kerület',
  'XVI. kerület',
  'XVII. kerület',
  'XVIII. kerület',
  'XIX. kerület',
  'XX. kerület',
  'XXI. kerület',
  'XXII. kerület',
  'XXIII. kerület',
];

export const hungarianCities = [
  'Budapest',
  'Debrecen',
  'Szeged',
  'Miskolc',
  'Pécs',
  'Győr',
  'Nyíregyháza',
  'Kecskemét',
  'Székesfehérvár',
  'Szombathely',
  'Érd',
  'Tatabánya',
  'Sopron',
  'Veszprém',
  'Eger',
];
